version: "3"

services:
  db:
    image: postgres:14-bullseye
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data    
    environment:
      - POSTGRES_DB=panopticon_db
      # - PGUSER='panoptis_postgres'
      - POSTGRES_USER='panoptis_postgres'
      - POSTGRES_PASSWORD='tIj!@;004rlkDFUBWEFfdsfx'
    networks:
      - djangonetwork
      
  app:
    build:
      context: . # Sets the directory containing a Dockerfile .
    ports:
      - "8000:8000"
    volumes:
      # Copy changes made to the project to image's working directory as changes are made.
      - .:/PANOpticon
    networks:
      - djangonetwork
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=panopticon_db
      - POSTGRES_USER='panoptis_postgres'
      - POSTGRES_PASSWORD='tIj!@;004rlkDFUBWEFfdsfx'
    depends_on:
      - db
    restart: always

networks:
  djangonetwork:
    driver: bridge

