version: "3"

services:
  db:
    image: postgres:14-bullseye
    env_file: .docker_envfile
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data:z
    restart: always

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      # Copy changes made to the project to image's working directory as changes are made.
      - .:/PANOpticon/
    env_file: .docker_envfile
    depends_on:
      - db
    restart: always
    command: >
      sh -c "python3 manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000
             "