# Generated by Django 4.1.5 on 2023-02-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cve_id', models.CharField(max_length=20)),
                ('epss', models.CharField(max_length=20)),            ],
            options={
                'verbose_name_plural': 'vulnerabilities',
            },
        ),
    ]
